<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class News extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared("INSERT INTO `news` (`id`, `title`, `summary`, `main`, `secondary`, `list`, `gallery`, `date`, `user_id`, `updated_by`, `edited_at`, `created_at`, `updated_at`) VALUES
        (5, 'Émission d\'un timbre-poste.', 'Émission d\'un timbre-poste consacré à “Hamadi Agrebi, le magicien du football tunisien”', 'Rendant hommage aux sportifs et athlètes qui ont contribué à travers les diverses disciplines à honorer le sport tunisien, à faire connaître notre pays et à hisser haut le drapeau national lord des évenements sportifs nationaux et internationaux , la Poste Tunisienne émet le 21 août 2021 un timbre-poste dédié à la légende du football tunisien et le magicien des générations, Hamadi Agrebi.  Ce timbre- poste ainsi que les autres produits philatéliques réalisés à cette occasion seront disponibles à la vente dans tous les bureaux de poste et via Internet à travers le site www.e-stamps.poste.tn à partir du samedi 21 août 2021.', 'Pour plus d’information : www.e-stamps.poste.tn , www.tunisia-stamps.tn', NULL, '1629776676Fp0Q5V2CVlkNodmG16ygkb2ZryD6CAkYn7d3cPJm.jpg', '2021-08-24 03:44:36', 2, NULL, NULL, '2021-08-24 03:44:36', '2021-08-24 03:44:36'),
        (6, 'Emission de deux timbres-poste.', 'Emission de deux timbres-poste sur le thème : Bijoux traditionnels méditerranéens', 'Dans le cadre de sa contribution active dans les activités de l’Union Postale pour la Méditerranée et compte tenu de son rôle important dans le développement de la coopération et du partenariat avec les institutions postales euro-méditerranéennes, la Poste Tunisienne émet le 15 juillet 2021, à l’instar des pays membres de l’Union pour la Méditerranée, deux timbres- poste sur le thème: \" Bijoux traditionnels méditerranéens \".  Ces deux timbres- poste ainsi que les autres produits philatéliques réalisés à cette occasion seront disponibles à la vente dans tous les bureaux de poste et via Internet à travers le site www.e-stamps.poste.tn à partir du jeudi 15 juillet 2021.', 'Pour plus d’information : www.e-stamps.poste.tn , www.tunisia-stamps.tn', NULL, '1629776767lceoeiDWfmWKJ97rBcExVzHQz6BR0KzV7euBSaFH.jpg|16297767673YkjKPPkISpqA7IFSNf5sVix1HxB6cqnQnJcjSEi.jpg', '2021-08-24 03:46:07', 2, NULL, NULL, '2021-08-24 03:46:07', '2021-08-24 03:46:07'),
        (7, 'L’horaire d’été pour l’ouverture des Bureaux de Poste.', 'L’horaire d’été pour l’ouverture des Bureaux de Poste, des Agences RapidPost et des Agences Colis Postaux à partir du 1er juillet jusqu’au 31 août 2021', 'La Poste Tunisienne informe sa clientèle que l’horaire d’été pour l’ouverture des Bureaux de Poste, des agences RapidPost et des agences Colis Postaux à partir du 1er juillet jusqu’au 31 août 2021 sera comme suit:', 'Il est à rappeler que 64 bureaux de poste et 25 agences RapidPost continuent à assurer une séance du travail les samedis de 9h00 à 12h15.', 'Lundi, mardi, mercredi et jeudi : de 7h30 jusqu’à 13h00.|Vendredi : de 7h30 jusqu’à 12h30.', NULL, '2021-08-24 03:47:24', 2, NULL, NULL, '2021-08-24 03:47:24', '2021-08-24 03:47:24'),
        (8, 'Emission d’un timbre-poste.', 'Emission d’un timbre-poste concernant le projet des Maisons de services \"Idarti\"', 'La Poste Tunisienne émet le 21 juin 2021, un timbre-poste pour faire mieux connaitre le projet des Maisons de services « Idarti », un projet national important qui vise à rapprocher les services administratifs des citoyens et qui mérite d’être inscrit dans l’histoire de l’administration tunisienne. Cette émission s’inscrit aussi dans le cadre de la célébration de la Journée des Nations Unies du service public, célébrée le 23 juin de chaque année.  Ce timbre- poste ainsi que les autres produits philatéliques réalisés à cette occasion seront disponibles à la vente dans tous les bureaux de poste et via Internet à travers le site www.e-stamps.poste.tn à partir du lundi 21 juin 2021.', 'Pour plus d’information : www.e-stamps.poste.tn , www.tunisia-stamps.tn', NULL, '16297769179PFJOOSce4vBvh6ZeJDKDnbyJpy7qvOTQAbwXPyL.jpg', '2021-08-24 03:48:37', 2, NULL, NULL, '2021-08-24 03:48:37', '2021-08-24 03:48:37'),
        (9, 'Hello', 'Testing', 'What\'s up', 'Nothing much', 'First: things firs.', '16298359531yCAmLRuibVVZl0N0nODx8UkaYlSRZqgM4BRQIzQ.jpg', '2021-08-24 20:12:33', 2, NULL, NULL, '2021-08-24 20:12:33', '2021-08-24 20:12:33'),
        (10, 'Convention de partenariat entre la Poste Tunisienne et la Compagnie Tunisienne de Navigation', 'Dans le cadre de l’application du proto', 'Dans le cadre de l’application du protocole d\'accord signé au cours du mois de janvier 2021, la Poste Tunisienne et la Compagnie Tunisienne de Navigation « CTN » ont signé le lundi 23 aout 2021 une convention de partenariat au siège de la Compagnie pour permettre aux clients de ladite compagnie d’acheter et de payer les billets d’une manière sécurisée par le biais de la plateforme de paiement à distance « MasterCard Payment Getway Services : MPGS ».  La convention de partenariat a été signée par M. Sami Mekki, PDG de la Poste Tunisienne et M. Imed Zammit, DG de la Compagnie Tunisienne de Navigation « CTN ».  A travers cette convention de partenariat, la Poste Tunisienne met à la disposition de la « CTN », sa plateforme de paiement à distance « MasterCard Payment Getway Services : MPGS » pour lui permettre d’accepter les paiements des billets moyennant les cartes de paiement électroniques nationales et internationales via les sites de vente en ligne de la Compagnie dans une première étape et à travers les agences de voyage accréditées dans une seconde étape.  Il est à signaler que la plateforme « MPGS » de la Poste Tunisienne est l’unique plateforme, opérationnelle, en Tunisie, qui accepte les moyens de paiement nationaux et internationaux selon les nouvelles normes et standards de sécurité internationaux et notamment ceux exigés par les compagnies aériennes et maritimes.  En outre, ce partenariat va permettre d’assurer la gestion des comptes en devises pour le rapatriement des fonds collectés via la plateforme MPGS provenant de la vente de billets à l’étranger. Ceci permettra le drainage des devises vers la Tunisie et l’augmentation des réserves de change à l’échelle nationale.  Cette convention constitue une première en Tunisie et en Afrique, entre un établissement financier national disposant d’une plateforme de paiement digital et une compagnie maritimes pour offrir une solution de paiement numérique développée par des compétences tunisiennes.', NULL, NULL, '1630155481NqXSBT823il8j9hvfKrtaF0NuYpJCGcbDVft5gxX.jpg', '2021-08-28 12:58:01', 2, 2, '2021-08-30 00:18:03', '2021-08-28 12:58:01', '2021-08-30 00:18:03')");
    }
}
